use std::fmt::Display;
use std::str::FromStr;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum Key {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Enter,
    Escape,
    Backspace,
    Tab,
    Space,
    Minus,
    Equal,
    LeftBracket,
    RightBracket,
    Backslash,
    NonusHash,
    Semicolon,
    Quote,
    Grave,
    Comma,
    Dot,
    Slash,
    NonusBackslash,
    CapsLock,
    ScrollLock,
    NumLock,
    LockingCapsLock,
    LockingNumLock,
    LockingScrollLock,
    LeftCtrl,
    LeftShift,
    LeftAlt,
    LeftGui,
    RightCtrl,
    RightShift,
    RightAlt,
    RightGui,
    International1,
    International2,
    International3,
    International4,
    International5,
    International6,
    International7,
    International8,
    International9,
    Language1,
    Language2,
    Language3,
    Language4,
    Language5,
    Language6,
    Language7,
    Language8,
    Language9,
    PrintScreen,
    Pause,
    Insert,
    Home,
    PageUp,
    Delete,
    End,
    PageDown,
    Right,
    Left,
    Down,
    Up,
    Application,
    KbPower,
    Execute,
    Help,
    Menu,
    Select,
    Stop,
    Again,
    Undo,
    Cut,
    Copy,
    Paste,
    Find,
    KbMute,
    KbVolumeUp,
    KbVolumeDown,
    AlternateErase,
    SystemRequest,
    Cancel,
    Clear,
    Prior,
    Return,
    Separator,
    Out,
    Oper,
    ClearAgain,
    Crsel,
    Exsel,
    SystemPower,
    SystemSleep,
    SystemWake,
    AudioMute,
    AudioVolUp,
    AudioVolDown,
    MediaNextTrack,
    MediaPrevTrack,
    MediaStop,
    MediaPlayPause,
    MediaSelect,
    MediaEject,
    Mail,
    Calculator,
    MyComputer,
    WwwSearch,
    WwwHome,
    WwwBack,
    WwwForward,
    WwwStop,
    WwwRefresh,
    WwwFavorites,
    MediaFastForward,
    MediaRewind,
    BrightnessUp,
    BrightnessDown,
    ControlPanel,
    Assistant,
    MissionControl,
    Launchpad,
    KpSlash,
    KpAsterisk,
    KpMinus,
    KpPlus,
    KpEnter,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    Kp0,
    KpDot,
    KpEqual,
    KpComma,
    KpEqualAs400,
    Df(String),
    Pdf(String),
    Mo(String),
    Lm(String, String),
    Lt(String, Box<Key>),
    Osl(String),
    Tg(String),
    To(String),
    Tt(String),
    #[default]
    No,
    Transparent,
}

impl Key {
    pub fn as_str(&self) -> String {
        match self {
            Self::Df(layer) => format!("DF({})", layer),
            Self::Pdf(layer) => format!("PDF({})", layer),
            Self::Mo(layer) => format!("MO({})", layer),
            Self::Lm(layer, mods) => format!("LM({}, {})", layer, mods),
            Self::Lt(layer, kc) => format!("LT({}, {})", layer, kc),
            Self::Osl(layer) => format!("OSL({})", layer),
            Self::Tg(layer) => format!("TG({})", layer),
            Self::To(layer) => format!("TO({})", layer),
            Self::Tt(layer) => format!("TT({})", layer),
            _ => self.static_str().to_string(),
        }
    }

    pub const fn static_str(&self) -> &'static str {
        match self {
            Self::A => "KC_A",
            Self::B => "KC_B",
            Self::C => "KC_C",
            Self::D => "KC_D",
            Self::E => "KC_E",
            Self::F => "KC_F",
            Self::G => "KC_G",
            Self::H => "KC_H",
            Self::I => "KC_I",
            Self::J => "KC_J",
            Self::K => "KC_K",
            Self::L => "KC_L",
            Self::M => "KC_M",
            Self::N => "KC_N",
            Self::O => "KC_O",
            Self::P => "KC_P",
            Self::Q => "KC_Q",
            Self::R => "KC_R",
            Self::S => "KC_S",
            Self::T => "KC_T",
            Self::U => "KC_U",
            Self::V => "KC_V",
            Self::W => "KC_W",
            Self::X => "KC_X",
            Self::Y => "KC_Y",
            Self::Z => "KC_Z",
            Self::Key1 => "KC_1",
            Self::Key2 => "KC_2",
            Self::Key3 => "KC_3",
            Self::Key4 => "KC_4",
            Self::Key5 => "KC_5",
            Self::Key6 => "KC_6",
            Self::Key7 => "KC_7",
            Self::Key8 => "KC_8",
            Self::Key9 => "KC_9",
            Self::Key0 => "KC_0",
            Self::F1 => "KC_F1",
            Self::F2 => "KC_F2",
            Self::F3 => "KC_F3",
            Self::F4 => "KC_F4",
            Self::F5 => "KC_F5",
            Self::F6 => "KC_F6",
            Self::F7 => "KC_F7",
            Self::F8 => "KC_F8",
            Self::F9 => "KC_F9",
            Self::F10 => "KC_F10",
            Self::F11 => "KC_F11",
            Self::F12 => "KC_F12",
            Self::F13 => "KC_F13",
            Self::F14 => "KC_F14",
            Self::F15 => "KC_F15",
            Self::F16 => "KC_F16",
            Self::F17 => "KC_F17",
            Self::F18 => "KC_F18",
            Self::F19 => "KC_F19",
            Self::F20 => "KC_F20",
            Self::F21 => "KC_F21",
            Self::F22 => "KC_F22",
            Self::F23 => "KC_F23",
            Self::F24 => "KC_F24",
            Self::Enter => "KC_ENT",
            Self::Escape => "KC_ESC",
            Self::Backspace => "KC_BSPC",
            Self::Tab => "KC_TAB",
            Self::Space => "KC_SPC",
            Self::Minus => "KC_MINS",
            Self::Equal => "KC_EQL",
            Self::LeftBracket => "KC_LBRC",
            Self::RightBracket => "KC_RBRC",
            Self::Backslash => "KC_BSLS",
            Self::NonusHash => "KC_NUHS",
            Self::Semicolon => "KC_SCLN",
            Self::Quote => "KC_QUOT",
            Self::Grave => "KC_GRV",
            Self::Comma => "KC_COMM",
            Self::Dot => "KC_DOT",
            Self::Slash => "KC_SLSH",
            Self::NonusBackslash => "KC_NUBS",
            Self::CapsLock => "KC_CAPS",
            Self::ScrollLock => "KC_SCRL",
            Self::NumLock => "KC_NUM",
            Self::LockingCapsLock => "KC_LCAP",
            Self::LockingNumLock => "KC_LNUM",
            Self::LockingScrollLock => "KC_LSCR",
            Self::LeftCtrl => "KC_LCTL",
            Self::LeftShift => "KC_LSFT",
            Self::LeftAlt => "KC_LALT",
            Self::LeftGui => "KC_LGUI",
            Self::RightCtrl => "KC_RCTL",
            Self::RightShift => "KC_RSFT",
            Self::RightAlt => "KC_RALT",
            Self::RightGui => "KC_RGUI",
            Self::International1 => "KC_INT1",
            Self::International2 => "KC_INT2",
            Self::International3 => "KC_INT3",
            Self::International4 => "KC_INT4",
            Self::International5 => "KC_INT5",
            Self::International6 => "KC_INT6",
            Self::International7 => "KC_INT7",
            Self::International8 => "KC_INT8",
            Self::International9 => "KC_INT9",
            Self::Language1 => "KC_LNG1",
            Self::Language2 => "KC_LNG2",
            Self::Language3 => "KC_LNG3",
            Self::Language4 => "KC_LNG4",
            Self::Language5 => "KC_LNG5",
            Self::Language6 => "KC_LNG6",
            Self::Language7 => "KC_LNG7",
            Self::Language8 => "KC_LNG8",
            Self::Language9 => "KC_LNG9",
            Self::PrintScreen => "KC_PSCR",
            Self::Pause => "KC_PAUS",
            Self::Insert => "KC_INS",
            Self::Home => "KC_HOME",
            Self::PageUp => "KC_PGUP",
            Self::Delete => "KC_DEL",
            Self::End => "KC_END",
            Self::PageDown => "KC_PGDN",
            Self::Right => "KC_RGHT",
            Self::Left => "KC_LEFT",
            Self::Down => "KC_DOWN",
            Self::Up => "KC_UP",
            Self::Application => "KC_APP",
            Self::KbPower => "KC_KB_POWER",
            Self::Execute => "KC_EXEC",
            Self::Help => "KC_HELP",
            Self::Menu => "KC_MENU",
            Self::Select => "KC_SLCT",
            Self::Stop => "KC_STOP",
            Self::Again => "KC_AGIN",
            Self::Undo => "KC_UNDO",
            Self::Cut => "KC_CUT",
            Self::Copy => "KC_COPY",
            Self::Paste => "KC_PSTE",
            Self::Find => "KC_FIND",
            Self::KbMute => "KC_KB_MUTE",
            Self::KbVolumeUp => "KC_KB_VOLUME_UP",
            Self::KbVolumeDown => "KC_KB_VOLUME_DOWN",
            Self::AlternateErase => "KC_ERAS",
            Self::SystemRequest => "KC_SYRQ",
            Self::Cancel => "KC_CNCL",
            Self::Clear => "KC_CLR",
            Self::Prior => "KC_PRIR",
            Self::Return => "KC_RETN",
            Self::Separator => "KC_SEPR",
            Self::Out => "KC_OUT",
            Self::Oper => "KC_OPER",
            Self::ClearAgain => "KC_CLAG",
            Self::Crsel => "KC_CRSL",
            Self::Exsel => "KC_EXSL",
            Self::SystemPower => "KC_PWR",
            Self::SystemSleep => "KC_SLEP",
            Self::SystemWake => "KC_WAKE",
            Self::AudioMute => "KC_MUTE",
            Self::AudioVolUp => "KC_VOLU",
            Self::AudioVolDown => "KC_VOLD",
            Self::MediaNextTrack => "KC_MNXT",
            Self::MediaPrevTrack => "KC_MPRV",
            Self::MediaStop => "KC_MSTP",
            Self::MediaPlayPause => "KC_MPLY",
            Self::MediaSelect => "KC_MSEL",
            Self::MediaEject => "KC_EJCT",
            Self::Mail => "KC_MAIL",
            Self::Calculator => "KC_CALC",
            Self::MyComputer => "KC_MYCM",
            Self::WwwSearch => "KC_WSCH",
            Self::WwwHome => "KC_WHOM",
            Self::WwwBack => "KC_WBAK",
            Self::WwwForward => "KC_WFWD",
            Self::WwwStop => "KC_WSTP",
            Self::WwwRefresh => "KC_WREF",
            Self::WwwFavorites => "KC_WFAV",
            Self::MediaFastForward => "KC_MFFD",
            Self::MediaRewind => "KC_MRWD",
            Self::BrightnessUp => "KC_BRIU",
            Self::BrightnessDown => "KC_BRID",
            Self::ControlPanel => "KC_CPNL",
            Self::Assistant => "KC_ASST",
            Self::MissionControl => "KC_MCTL",
            Self::Launchpad => "KC_LPAD",
            Self::KpSlash => "KC_PSLS",
            Self::KpAsterisk => "KC_PAST",
            Self::KpMinus => "KC_PMNS",
            Self::KpPlus => "KC_PPLS",
            Self::KpEnter => "KC_PENT",
            Self::Kp1 => "KC_P1",
            Self::Kp2 => "KC_P2",
            Self::Kp3 => "KC_P3",
            Self::Kp4 => "KC_P4",
            Self::Kp5 => "KC_P5",
            Self::Kp6 => "KC_P6",
            Self::Kp7 => "KC_P7",
            Self::Kp8 => "KC_P8",
            Self::Kp9 => "KC_P9",
            Self::Kp0 => "KC_P0",
            Self::KpDot => "KC_PDOT",
            Self::KpEqual => "KC_PEQL",
            Self::KpComma => "KC_PCMM",
            Self::KpEqualAs400 => "KC_KP_EQUAL_AS400",
            Self::No => "KC_NO",
            Self::Transparent => "KC_TRNS",
            _ => "KC_NO",
        }
    }
}

impl Display for Key {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl FromStr for Key {
    type Err = crate::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let s = s.trim();
        if s.starts_with("DF(") && s.ends_with(')') {
            return Ok(Self::Df(s[3..s.len() - 1].trim().to_string()));
        }
        if s.starts_with("PDF(") && s.ends_with(')') {
            return Ok(Self::Pdf(s[4..s.len() - 1].trim().to_string()));
        }
        if s.starts_with("MO(") && s.ends_with(')') {
            return Ok(Self::Mo(s[3..s.len() - 1].trim().to_string()));
        }
        if s.starts_with("LM(") && s.ends_with(')') {
            let inner = &s[3..s.len() - 1];
            if let Some((layer, mods)) = inner.split_once(',') {
                return Ok(Self::Lm(layer.trim().to_string(), mods.trim().to_string()));
            }
        }
        if s.starts_with("LT(") && s.ends_with(')') {
            let inner = &s[3..s.len() - 1];
            if let Some((layer, kc)) = inner.split_once(',') {
                return Ok(Self::Lt(
                    layer.trim().to_string(),
                    Box::new(Self::from_str(kc.trim())?),
                ));
            }
        }
        if s.starts_with("OSL(") && s.ends_with(')') {
            return Ok(Self::Osl(s[4..s.len() - 1].trim().to_string()));
        }
        if s.starts_with("TG(") && s.ends_with(')') {
            return Ok(Self::Tg(s[3..s.len() - 1].trim().to_string()));
        }
        if s.starts_with("TO(") && s.ends_with(')') {
            return Ok(Self::To(s[3..s.len() - 1].trim().to_string()));
        }
        if s.starts_with("TT(") && s.ends_with(')') {
            return Ok(Self::Tt(s[3..s.len() - 1].trim().to_string()));
        }

        match s {
            "KC_A" | "a" | "A" => Ok(Self::A),
            "KC_B" | "b" | "B" => Ok(Self::B),
            "KC_C" | "c" | "C" => Ok(Self::C),
            "KC_D" | "d" | "D" => Ok(Self::D),
            "KC_E" | "e" | "E" => Ok(Self::E),
            "KC_F" | "f" | "F" => Ok(Self::F),
            "KC_G" | "g" | "G" => Ok(Self::G),
            "KC_H" | "h" | "H" => Ok(Self::H),
            "KC_I" | "i" | "I" => Ok(Self::I),
            "KC_J" | "j" | "J" => Ok(Self::J),
            "KC_K" | "k" | "K" => Ok(Self::K),
            "KC_L" | "l" | "L" => Ok(Self::L),
            "KC_M" | "m" | "M" => Ok(Self::M),
            "KC_N" | "n" | "N" => Ok(Self::N),
            "KC_O" | "o" | "O" => Ok(Self::O),
            "KC_P" | "p" | "P" => Ok(Self::P),
            "KC_Q" | "q" | "Q" => Ok(Self::Q),
            "KC_R" | "r" | "R" => Ok(Self::R),
            "KC_S" | "s" | "S" => Ok(Self::S),
            "KC_T" | "t" | "T" => Ok(Self::T),
            "KC_U" | "u" | "U" => Ok(Self::U),
            "KC_V" | "v" | "V" => Ok(Self::V),
            "KC_W" | "w" | "W" => Ok(Self::W),
            "KC_X" | "x" | "X" => Ok(Self::X),
            "KC_Y" | "y" | "Y" => Ok(Self::Y),
            "KC_Z" | "z" | "Z" => Ok(Self::Z),
            "KC_1" | "1" | "!" => Ok(Self::Key1),
            "KC_2" | "2" | "@" => Ok(Self::Key2),
            "KC_3" | "3" | "#" => Ok(Self::Key3),
            "KC_4" | "4" | "$" => Ok(Self::Key4),
            "KC_5" | "5" | "%" => Ok(Self::Key5),
            "KC_6" | "6" | "^" => Ok(Self::Key6),
            "KC_7" | "7" | "&" => Ok(Self::Key7),
            "KC_8" | "8" | "*" => Ok(Self::Key8),
            "KC_9" | "9" | "(" => Ok(Self::Key9),
            "KC_0" | "0" | ")" => Ok(Self::Key0),
            "KC_F1" | "F1" => Ok(Self::F1),
            "KC_F2" | "F2" => Ok(Self::F2),
            "KC_F3" | "F3" => Ok(Self::F3),
            "KC_F4" | "F4" => Ok(Self::F4),
            "KC_F5" | "F5" => Ok(Self::F5),
            "KC_F6" | "F6" => Ok(Self::F6),
            "KC_F7" | "F7" => Ok(Self::F7),
            "KC_F8" | "F8" => Ok(Self::F8),
            "KC_F9" | "F9" => Ok(Self::F9),
            "KC_F10" | "F10" => Ok(Self::F10),
            "KC_F11" | "F11" => Ok(Self::F11),
            "KC_F12" | "F12" => Ok(Self::F12),
            "KC_F13" | "F13" => Ok(Self::F13),
            "KC_F14" | "F14" => Ok(Self::F14),
            "KC_F15" | "F15" => Ok(Self::F15),
            "KC_F16" | "F16" => Ok(Self::F16),
            "KC_F17" | "F17" => Ok(Self::F17),
            "KC_F18" | "F18" => Ok(Self::F18),
            "KC_F19" | "F19" => Ok(Self::F19),
            "KC_F20" | "F20" => Ok(Self::F20),
            "KC_F21" | "F21" => Ok(Self::F21),
            "KC_F22" | "F22" => Ok(Self::F22),
            "KC_F23" | "F23" => Ok(Self::F23),
            "KC_F24" | "F24" => Ok(Self::F24),
            "KC_ENTER" | "KC_ENT" => Ok(Self::Enter),
            "KC_ESCAPE" | "KC_ESC" => Ok(Self::Escape),
            "KC_BACKSPACE" | "KC_BSPC" => Ok(Self::Backspace),
            "KC_TAB" => Ok(Self::Tab),
            "KC_SPACE" | "KC_SPC" => Ok(Self::Space),
            "KC_MINUS" | "KC_MINS" => Ok(Self::Minus),
            "KC_EQUAL" | "KC_EQL" => Ok(Self::Equal),
            "KC_LEFT_BRACKET" | "KC_LBRC" => Ok(Self::LeftBracket),
            "KC_RIGHT_BRACKET" | "KC_RBRC" => Ok(Self::RightBracket),
            "KC_BACKSLASH" | "KC_BSLS" => Ok(Self::Backslash),
            "KC_NONUS_HASH" | "KC_NUHS" => Ok(Self::NonusHash),
            "KC_SEMICOLON" | "KC_SCLN" => Ok(Self::Semicolon),
            "KC_QUOTE" | "KC_QUOT" => Ok(Self::Quote),
            "KC_GRAVE" | "KC_GRV" => Ok(Self::Grave),
            "KC_COMMA" | "KC_COMM" => Ok(Self::Comma),
            "KC_DOT" => Ok(Self::Dot),
            "KC_SLASH" | "KC_SLSH" => Ok(Self::Slash),
            "KC_NONUS_BACKSLASH" | "KC_NUBS" => Ok(Self::NonusBackslash),
            "KC_CAPS_LOCK" | "KC_CAPS" => Ok(Self::CapsLock),
            "KC_SCROLL_LOCK" | "KC_SCRL" | "KC_BRMD" => Ok(Self::ScrollLock),
            "KC_NUM_LOCK" | "KC_NUM" => Ok(Self::NumLock),
            "KC_LOCKING_CAPS_LOCK" | "KC_LCAP" => Ok(Self::LockingCapsLock),
            "KC_LOCKING_NUM_LOCK" | "KC_LNUM" => Ok(Self::LockingNumLock),
            "KC_LOCKING_SCROLL_LOCK" | "KC_LSCR" => Ok(Self::LockingScrollLock),
            "KC_LEFT_CTRL" | "KC_LCTL" => Ok(Self::LeftCtrl),
            "KC_LEFT_SHIFT" | "KC_LSFT" => Ok(Self::LeftShift),
            "KC_LEFT_ALT" | "KC_LALT" | "KC_LOPT" => Ok(Self::LeftAlt),
            "KC_LEFT_GUI" | "KC_LGUI" | "KC_LCMD" | "KC_LWIN" => Ok(Self::LeftGui),
            "KC_RIGHT_CTRL" | "KC_RCTL" => Ok(Self::RightCtrl),
            "KC_RIGHT_SHIFT" | "KC_RSFT" => Ok(Self::RightShift),
            "KC_RIGHT_ALT" | "KC_RALT" | "KC_ROPT" | "KC_ALGR" => Ok(Self::RightAlt),
            "KC_RIGHT_GUI" | "KC_RGUI" | "KC_RCMD" | "KC_RWIN" => Ok(Self::RightGui),
            "KC_INTERNATIONAL_1" | "KC_INT1" => Ok(Self::International1),
            "KC_INTERNATIONAL_2" | "KC_INT2" => Ok(Self::International2),
            "KC_INTERNATIONAL_3" | "KC_INT3" => Ok(Self::International3),
            "KC_INTERNATIONAL_4" | "KC_INT4" => Ok(Self::International4),
            "KC_INTERNATIONAL_5" | "KC_INT5" => Ok(Self::International5),
            "KC_INTERNATIONAL_6" | "KC_INT6" => Ok(Self::International6),
            "KC_INTERNATIONAL_7" | "KC_INT7" => Ok(Self::International7),
            "KC_INTERNATIONAL_8" | "KC_INT8" => Ok(Self::International8),
            "KC_INTERNATIONAL_9" | "KC_INT9" => Ok(Self::International9),
            "KC_LANGUAGE_1" | "KC_LNG1" => Ok(Self::Language1),
            "KC_LANGUAGE_2" | "KC_LNG2" => Ok(Self::Language2),
            "KC_LANGUAGE_3" | "KC_LNG3" => Ok(Self::Language3),
            "KC_LANGUAGE_4" | "KC_LNG4" => Ok(Self::Language4),
            "KC_LANGUAGE_5" | "KC_LNG5" => Ok(Self::Language5),
            "KC_LANGUAGE_6" | "KC_LNG6" => Ok(Self::Language6),
            "KC_LANGUAGE_7" | "KC_LNG7" => Ok(Self::Language7),
            "KC_LANGUAGE_8" | "KC_LNG8" => Ok(Self::Language8),
            "KC_LANGUAGE_9" | "KC_LNG9" => Ok(Self::Language9),
            "KC_PRINT_SCREEN" | "KC_PSCR" => Ok(Self::PrintScreen),
            "KC_PAUSE" | "KC_PAUS" | "KC_BRK" | "KC_BRMU" => Ok(Self::Pause),
            "KC_INSERT" | "KC_INS" => Ok(Self::Insert),
            "KC_HOME" => Ok(Self::Home),
            "KC_PAGE_UP" | "KC_PGUP" => Ok(Self::PageUp),
            "KC_DELETE" | "KC_DEL" => Ok(Self::Delete),
            "KC_END" => Ok(Self::End),
            "KC_PAGE_DOWN" | "KC_PGDN" => Ok(Self::PageDown),
            "KC_RIGHT" | "KC_RGHT" => Ok(Self::Right),
            "KC_LEFT" => Ok(Self::Left),
            "KC_DOWN" => Ok(Self::Down),
            "KC_UP" => Ok(Self::Up),
            "KC_APPLICATION" | "KC_APP" => Ok(Self::Application),
            "KC_KB_POWER" => Ok(Self::KbPower),
            "KC_EXECUTE" | "KC_EXEC" => Ok(Self::Execute),
            "KC_HELP" => Ok(Self::Help),
            "KC_MENU" => Ok(Self::Menu),
            "KC_SELECT" | "KC_SLCT" => Ok(Self::Select),
            "KC_STOP" => Ok(Self::Stop),
            "KC_AGAIN" | "KC_AGIN" => Ok(Self::Again),
            "KC_UNDO" => Ok(Self::Undo),
            "KC_CUT" => Ok(Self::Cut),
            "KC_COPY" => Ok(Self::Copy),
            "KC_PASTE" | "KC_PSTE" => Ok(Self::Paste),
            "KC_FIND" => Ok(Self::Find),
            "KC_KB_MUTE" => Ok(Self::KbMute),
            "KC_KB_VOLUME_UP" => Ok(Self::KbVolumeUp),
            "KC_KB_VOLUME_DOWN" => Ok(Self::KbVolumeDown),
            "KC_ALTERNATE_ERASE" | "KC_ERAS" => Ok(Self::AlternateErase),
            "KC_SYSTEM_REQUEST" | "KC_SYRQ" => Ok(Self::SystemRequest),
            "KC_CANCEL" | "KC_CNCL" => Ok(Self::Cancel),
            "KC_CLEAR" | "KC_CLR" => Ok(Self::Clear),
            "KC_PRIOR" | "KC_PRIR" => Ok(Self::Prior),
            "KC_RETURN" | "KC_RETN" => Ok(Self::Return),
            "KC_SEPARATOR" | "KC_SEPR" => Ok(Self::Separator),
            "KC_OUT" => Ok(Self::Out),
            "KC_OPER" => Ok(Self::Oper),
            "KC_CLEAR_AGAIN" | "KC_CLAG" => Ok(Self::ClearAgain),
            "KC_CRSEL" | "KC_CRSL" => Ok(Self::Crsel),
            "KC_EXSEL" | "KC_EXSL" => Ok(Self::Exsel),
            "KC_SYSTEM_POWER" | "KC_PWR" => Ok(Self::SystemPower),
            "KC_SYSTEM_SLEEP" | "KC_SLEP" => Ok(Self::SystemSleep),
            "KC_SYSTEM_WAKE" | "KC_WAKE" => Ok(Self::SystemWake),
            "KC_AUDIO_MUTE" | "KC_MUTE" => Ok(Self::AudioMute),
            "KC_AUDIO_VOL_UP" | "KC_VOLU" => Ok(Self::AudioVolUp),
            "KC_AUDIO_VOL_DOWN" | "KC_VOLD" => Ok(Self::AudioVolDown),
            "KC_MEDIA_NEXT_TRACK" | "KC_MNXT" => Ok(Self::MediaNextTrack),
            "KC_MEDIA_PREV_TRACK" | "KC_MPRV" => Ok(Self::MediaPrevTrack),
            "KC_MEDIA_STOP" | "KC_MSTP" => Ok(Self::MediaStop),
            "KC_MEDIA_PLAY_PAUSE" | "KC_MPLY" => Ok(Self::MediaPlayPause),
            "KC_MEDIA_SELECT" | "KC_MSEL" => Ok(Self::MediaSelect),
            "KC_MEDIA_EJECT" | "KC_EJCT" => Ok(Self::MediaEject),
            "KC_MAIL" => Ok(Self::Mail),
            "KC_CALCULATOR" | "KC_CALC" => Ok(Self::Calculator),
            "KC_MY_COMPUTER" | "KC_MYCM" => Ok(Self::MyComputer),
            "KC_WWW_SEARCH" | "KC_WSCH" => Ok(Self::WwwSearch),
            "KC_WWW_HOME" | "KC_WHOM" => Ok(Self::WwwHome),
            "KC_WWW_BACK" | "KC_WBAK" => Ok(Self::WwwBack),
            "KC_WWW_FORWARD" | "KC_WFWD" => Ok(Self::WwwForward),
            "KC_WWW_STOP" | "KC_WSTP" => Ok(Self::WwwStop),
            "KC_WWW_REFRESH" | "KC_WREF" => Ok(Self::WwwRefresh),
            "KC_WWW_FAVORITES" | "KC_WFAV" => Ok(Self::WwwFavorites),
            "KC_MEDIA_FAST_FORWARD" | "KC_MFFD" => Ok(Self::MediaFastForward),
            "KC_MEDIA_REWIND" | "KC_MRWD" => Ok(Self::MediaRewind),
            "KC_BRIGHTNESS_UP" | "KC_BRIU" => Ok(Self::BrightnessUp),
            "KC_BRIGHTNESS_DOWN" | "KC_BRID" => Ok(Self::BrightnessDown),
            "KC_CONTROL_PANEL" | "KC_CPNL" => Ok(Self::ControlPanel),
            "KC_ASSISTANT" | "KC_ASST" => Ok(Self::Assistant),
            "KC_MISSION_CONTROL" | "KC_MCTL" => Ok(Self::MissionControl),
            "KC_LAUNCHPAD" | "KC_LPAD" => Ok(Self::Launchpad),
            "KC_KP_SLASH" | "KC_PSLS" => Ok(Self::KpSlash),
            "KC_KP_ASTERISK" | "KC_PAST" => Ok(Self::KpAsterisk),
            "KC_KP_MINUS" | "KC_PMNS" => Ok(Self::KpMinus),
            "KC_KP_PLUS" | "KC_PPLS" => Ok(Self::KpPlus),
            "KC_KP_ENTER" | "KC_PENT" => Ok(Self::KpEnter),
            "KC_KP_1" | "KC_P1" => Ok(Self::Kp1),
            "KC_KP_2" | "KC_P2" => Ok(Self::Kp2),
            "KC_KP_3" | "KC_P3" => Ok(Self::Kp3),
            "KC_KP_4" | "KC_P4" => Ok(Self::Kp4),
            "KC_KP_5" | "KC_P5" => Ok(Self::Kp5),
            "KC_KP_6" | "KC_P6" => Ok(Self::Kp6),
            "KC_KP_7" | "KC_P7" => Ok(Self::Kp7),
            "KC_KP_8" | "KC_P8" => Ok(Self::Kp8),
            "KC_KP_9" | "KC_P9" => Ok(Self::Kp9),
            "KC_KP_0" | "KC_P0" => Ok(Self::Kp0),
            "KC_KP_DOT" | "KC_PDOT" => Ok(Self::KpDot),
            "KC_KP_EQUAL" | "KC_PEQL" => Ok(Self::KpEqual),
            "KC_KP_COMMA" | "KC_PCMM" => Ok(Self::KpComma),
            "KC_KP_EQUAL_AS400" => Ok(Self::KpEqualAs400),
            "KC_NO" | "XXXXXXX" => Ok(Self::No),
            "KC_TRANSPARENT" | "KC_TRNS" | "_______" => Ok(Self::Transparent),
            _ => Err(crate::Error::ParseKey(s.to_string())),
        }
    }
}
